import 'dart:convert';
import 'dart:io';

import '../models/manidoc_project.dart';
import 'html_exporter.dart';
import 'workspace_service.dart';

/// Web一括出力: 全プロジェクトをHTML化し、一覧ポータル(index.html)を生成する。
class PortalExporter {
  final WorkspaceService workspace;

  PortalExporter(this.workspace);

  String _esc(String s) => const HtmlEscape().convert(s);

  Future<String> export(List<ManidocProject> projects, String title,
      {bool includeToc = true,
      bool numbering = true,
      bool tts = false,
      double ttsSpeed = 1.0,
      double articleFontSize = 14}) async {
    final stamp = DateTime.now()
        .toIso8601String()
        .replaceAll(RegExp(r'[:.]'), '-')
        .substring(0, 19);
    final outDir =
        '${workspace.workspacePath}${Platform.pathSeparator}web_portal_$stamp';
    await Directory(outDir).create(recursive: true);

    final exporter = HtmlExporter(workspace);
    final cards = StringBuffer();
    for (final project in projects) {
      final safeName =
          project.name.replaceAll(RegExp(r'[\\/:*?"<>|]'), '_');
      await exporter.export(
        project,
        '$outDir${Platform.pathSeparator}$safeName',
        includeToc: includeToc,
        numbering: numbering,
        tts: tts,
        ttsSpeed: ttsSpeed,
        articleFontSize: articleFontSize,
        themeCss: await workspace.readThemeCss(project.themeCssFileName),
      );
      final updated =
          project.lastModifiedAt.toLocal().toString().substring(0, 16);
      cards.writeln('''
<a class="card" href="./${Uri.encodeComponent(safeName)}/index.html">
  <div class="card-tag">${project.tag.isEmpty ? '&nbsp;' : _esc(project.tag)}</div>
  <div class="card-title">${_esc(project.name)}</div>
  <div class="card-meta">更新: $updated</div>
</a>''');
    }

    final indexHtml = '''
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${_esc(title)}</title>
<style>
:root { --bg:#f4f5f7; --fg:#1a1a2e; --card:#fff; --accent:#4361ee; --muted:#6c757d; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#16161e; --fg:#e8e8f0; --card:#1f1f2b; --accent:#7b9aff; --muted:#9aa0a6; }
}
body { margin:0; background:var(--bg); color:var(--fg);
  font-family:"Segoe UI","Hiragino Sans","Noto Sans JP",sans-serif; }
header { padding:2.5rem 1.5rem 1rem; max-width:1080px; margin:0 auto; }
h1 { margin:0; }
.grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(260px,1fr));
  gap:1rem; padding:1.5rem; max-width:1080px; margin:0 auto; }
.card { background:var(--card); border-radius:12px; padding:1.2rem; text-decoration:none;
  color:var(--fg); box-shadow:0 2px 8px rgba(0,0,0,0.08); transition:transform .15s; }
.card:hover { transform:translateY(-3px); }
.card-tag { font-size:.75rem; color:var(--accent); font-weight:600; min-height:1.1em; }
.card-title { font-size:1.15rem; font-weight:700; margin:.4rem 0; }
.card-meta { font-size:.8rem; color:var(--muted); }
footer { text-align:center; color:var(--muted); font-size:.85rem; padding:2rem 0; }
</style>
</head>
<body>
<header><h1>${_esc(title)}</h1></header>
<div class="grid">
$cards
</div>
<footer>Generated by openManidoc</footer>
</body>
</html>
''';
    await File('$outDir${Platform.pathSeparator}index.html')
        .writeAsString(indexHtml);
    return outDir;
  }
}
